version: 2.1

commands: 
  install-dependencies:
    steps:
      - checkout
      - restore_cache:
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run: yarn install
      - save_cache:
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules

jobs:
  client-lint-and-tests:
    docker:
      - image: cimg/node:14.17.0
    steps:
      - install-dependencies
        working_directory: ~/project/management
      - run:
          name: Run lint
          command: yarn lint
          working_directory: ~/project/client
      - run:
          name: Run tests
          command: yarn test
          working_directory: ~/project/client

  management-lint-and-tests:
    docker:
      - image: cimg/node:14.17.0
    steps:
      - install-dependencies
        working_directory: ~/project/management
      - run:
          name: Run lint
          command: yarn lint
          working_directory: ~/project/management
      - run:
          name: Run tests
          command: yarn test
          working_directory: ~/project/management

  popup-lint: 
    docker:
      - image: cimg/node:14.17.0
    steps:
      - install-dependencies
      - run:
          name: Run lint
          command: yarn lint
          working_directory: ~/project/popup

workflows:
  test-on-push:
    jobs:
      - client-lint-and-tests
      - management-lint-and-tests
      - popup-lint
