version: 2.1

commands: 
  

jobs:
  install-dependencies:
    parameters:
      package: 
        type: string
    working_directory: << parameters.package >>
    docker:
      - image: cimg/node:14.17.0
    steps:
      - checkout
      

  client-lint-and-tests:
    docker:
      - image: cimg/node:14.17.0
    steps:
      - checkout
      - run: 
          command: yarn install
          working_directory: client
      - run:
          name: Run lint
          command: yarn lint
          working_directory: client

  management-lint-and-tests:
    docker:
      - image: cimg/node:14.17.0
    steps:
      - install-dependencies
      - run:
          name: Run lint
          command: yarn lint
      - run:
          name: Run tests
          command: yarn test

  popup-lint: 
    docker:
      - image: cimg/node:14.17.0
    steps:
      - install-dependencies
      - run:
          name: Run lint
          command: yarn lint
          working_directory: ~/project/popup

workflows:
  test-on-push:
    jobs:
      - client-lint-and-tests
