version: 2.1

jobs:
  trigger-workflow:
    docker:
      - image: cimg/node:14.17.0
    steps: 
      - checkout
      - run : git diff --no-commit-id --name-only -r `git log -n 2 --oneline --pretty=format:"%h" | tail -n1` | cut -d/ -f1 | sort -u

  lint-and-tests:
    parameters:
      package: 
        type: string
    working_directory: ~/project/<< parameters.package >>
    docker:
      - image: cimg/node:14.17.0
    steps:
      - checkout:
          path: ~/project
      - restore_cache:
          keys:
            - yarn-packages-<< parameters.package >>
      - run: 
          command: yarn install
          
      - save_cache:
          key: yarn-packages-<< parameters.package >>
          paths:
            - ./node_modules
      - run:
          name: Run lint
          command: yarn lint

      - unless: 
          condition:
            equal: ["popup", << parameters.package >>]
          steps: 
            - run: 
                name: Run tests
                command: yarn test


workflows:
  test-on-push:
    jobs:
      - trigger-workflow
      - lint-and-tests:
          name: client-lint-and-tests
          package: client
      - lint-and-tests:
          name: management-lint-and-tests
          package: management
      - lint-and-tests:
          name: popup-lint
          package: popup
