version: 2.1

parameters: 
  client:
    type: boolean
    default: false
  management:
    type: boolean
    default: false
  popup:
    type: boolean
    default: false
  trigger: 
    type: boolean
    default: true

jobs:
  trigger-workflow:
    docker:
      - image: cimg/node:14.17.0
    steps: 
      - checkout
      - run : ./.circleci/trigger-workflow.sh

  lint-and-tests:
    parameters:
      package: 
        type: string
    working_directory: ~/project/<< parameters.package >>
    docker:
      - image: cimg/node:14.17.0
    steps:
      - checkout:
          path: ~/project
      - restore_cache:
          keys:
            - yarn-packages-<< parameters.package >>
      - run: 
          command: yarn install
          
      - save_cache:
          key: yarn-packages-<< parameters.package >>
          paths:
            - ./node_modules
      - run:
          name: Run lint
          command: yarn lint

      - unless: 
          condition:
            equal: ["popup", << parameters.package >>]
          steps: 
            - run: 
                name: Run tests
                command: yarn test

workflows:
  trigger:
    when: << pipeline.parameters.trigger >>
    jobs:
      - trigger-workflow
  client-lint-and-tests:
    when: << pipeline.parameters.client >>
    jobs:
      - lint-and-tests:
          package: client
  management-lint-and-tests:
    when: << pipeline.parameters.management >>
    jobs:
      - lint-and-tests:
          package: management
  popup-lint:
    when: << pipeline.parameters.popup >>
    jobs:
      - lint-and-tests:
          package: popup
